language: ruby
cache: bundler

rvm:
  - 1.9
  - 2.2

env:
  matrix:
    - SUITE=foo
    - SUITE=bar
  global:
    - SOME_GLOBAL_VAR=on

before_script:
- env

script: bundle exec rake $SUITE

notifications:
  webhooks:
    urls:
      - http://104.236.53.210:9292/tci
